modLoader = "kotlinforforge"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPL 3.0"

[[mods]]
modId = "bountiful"
version = "${version}"
displayName = "Bountiful"
authors = "Ejektaflex"
description = '''
Bountiful adds bounty boards to the world.
'''
#logoFile = ""

[[mixins]]
config = "bountiful.mixins.json"

[[dependencies.bountiful]]
modId = "neoforge"
type="required"
versionRange = "[20.2.88,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bountiful]]
modId = "kambrik"
type="required"
versionRange = "${kambrik_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.bountiful]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"
